// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const CALL_README_REQUEST = 'CALL_README_REQUEST';
export const CALL_README_SUCCESS = 'CALL_README_SUCCESS';
export const CALL_README_FAIL = 'CALL_README_FAIL';

export const SET_UI_ELEMENT = 'SET_UI_ELEMENT';

